### ISSUE TITLE
CI/CD ECS deployment failing due to StudentDashboard error

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/edu-setu-group26-proj2#1]
Please refer to the attached screenshot.
![image](https://user-images.githubusercontent.com/30636208/203509364-d1d6e0f6-0e17-4cd2-88e7-357c7509739e.png)

This error occurs when running the CI/CD workflow to deploy the docker image to AWS ECR. 
Any idea how to fix this?

**Comment by rahulrk2303** [comment]
The issue was due to two different folder names called components and Components. 
![image](https://user-images.githubusercontent.com/30636208/203522064-03efe7ca-97ba-4f8b-9938-10505a620b75.png)

Fixed it by removing the components folder and merging all files inside the Components folder.

**Comment by rahulrk2303** [comment]
https://github.com/ekanshsinghal/edu-setu-group26-proj2/commit/976bfced6da8dfb23cd41c26bfd11a4f34b3a77c

**Comment by ekanshsinghal** [comment]
Should be fixed.. can you try now?

**Comment by rahulrk2303** [comment]
Looks like the "CI" workflow is failing. Please check again.

**Comment by ekanshsinghal** [comment]
fixed the test case and "CI" workflow
