### ISSUE TITLE
get_all_postings_by_professor Issue

### ISSUE THREAD

**Issue by sbkrishna123** [ekanshsinghal/edu-setu-group26-proj2#11]
This API is not working. Please take a look.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/89660642/205457371-9b1e8cb5-cb93-46ab-821d-c9970235b282.png">

**Comment by rahulrk2303** [comment]
What's this? Is this something we implemented or was it already present as part of the previous code?

**Comment by gowtham-sathyan** [comment]
I think it would have been some error while the code was being deployed. @sbkrishna123 if this isn't an issue anymore, please close it.

**Comment by sbkrishna123** [comment]
Yes. This got fixed once the global connections were removed. So closing the issue now
