### ISSUE TITLE
Requesting email as part of request in update_application api

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/edu-setu-group26-proj2#14]
@app.route("/update_application", methods=["POST"])

Currently the following request is sent:
/update_application [POST]
    Request:
    {
        application_id: number,
        status: string (This should be overwritten in the DB by API),
    remarks: string
    }

I would also like to have the student's email as part of the request. 

Working on the send email api

**Comment by ekanshsinghal** [comment]
done
