### ISSUE TITLE
Saved Jobs functionality not working

### ISSUE THREAD

**Issue by gowtham-sathyan** [ekanshsinghal/edu-setu-group26-proj2#3]

**Comment by rahulrk2303** [comment]
What's the issue here? Add description please.

**Comment by gowtham-sathyan** [comment]
Clicking on saved jobs within the student dashboard does nothing. It should retrieve the jobs saved by that particular student.

**Comment by rahulrk2303** [comment]
This is fixed right?

**Comment by gowtham-sathyan** [comment]
Test it once and close the issue.

**Comment by gowtham-sathyan** [comment]
Tested. Closing
