### ISSUE TITLE
Sorting department not working

### ISSUE THREAD

**Issue by gowtham-sathyan** [ekanshsinghal/edu-setu-group26-proj2#4]
Sorting job openings using department is not working in student dashboard

**Comment by rahulrk2303** [comment]
Is it a backend issue?

**Comment by gowtham-sathyan** [comment]
Can't be. It is handled in frontend. Although, I haven't checked fully. @ekanshsinghal if you check and find it is a backend issue, let me know and I'll fix it.

**Comment by ekanshsinghal** [comment]
@gowtham-sathyan This is due to a data issue. This 1 job has department set as null. 
Please remove this job, from db or add department.
![image](https://user-images.githubusercontent.com/15945880/205418190-26e06e21-b481-4dad-aafc-b291a686e606.png)

**Comment by gowtham-sathyan** [comment]
Entering the department is optional on the register page. So, either that has to be made a required field or the sorting has to be handled for null values as well.

Edit: I have fixed the data in the DB manually for now, but this issue needs its logic to be fixed.

**Comment by rahulrk2303** [comment]
Let's make the field mandatory. Should be an easy fix. Existing database values can be updated manually.

**Comment by sbkrishna123** [comment]
Made department mandatory. Should be fixed now
