### ISSUE TITLE
Hovering over the edit option displays as test

### ISSUE THREAD

**Issue by gowtham-sathyan** [ekanshsinghal/edu-setu-group26-proj2#5]
![image](https://user-images.githubusercontent.com/37440294/205202313-0d55fe32-220f-42fd-a957-87209dfdbb8e.png)

It is in the professor dashboard, in the applications tab.

**Comment by rahulrk2303** [comment]
It should be changed to "Edit" right?

**Comment by gowtham-sathyan** [comment]
Probably. It just shouldn't be "test".

**Comment by ekanshsinghal** [comment]
Removed the tooltip all together
