### ISSUE TITLE
Secure .pem file

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/edu-setu-group26-proj2#6]
The private key file needs to be secured. https://github.com/ekanshsinghal/edu-setu-group26-proj2/blob/main/code/backend/admin/ewallet.pem

**Comment by ekanshsinghal** [comment]
As per this link we need to create a base64 encode string and then use that in github action. I'll let you know once i have created the encoded string in github secrets.

**Comment by ekanshsinghal** [comment]
![image](https://user-images.githubusercontent.com/15945880/205413246-664be2e8-0cb8-467f-9562-f18a4bd3dd53.png)
@rahulrk2303  Now you can use this.

**Comment by rahulrk2303** [comment]
Great! You have all the contents of the pem file in secret right? I have replaced all the file contents with just this secret variable. Will test if it works this way.

**Comment by ekanshsinghal** [comment]
Yes i encoded the entire file itself
