### ISSUE TITLE
AWS credentials exposed

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/edu-setu-group26-proj2#7]
The aws workflow file has some secrets exposed. 
AWS_SECRET_ACCESS_KEY and AWS_ACCESS_ID need to be secured.

**Comment by rahulrk2303** [comment]
@ekanshsinghal Can you please create the secrets in Github Secret manager? I have updated the workflow file to access secrets from GitHub.

**Comment by ekanshsinghal** [comment]
Done
