### ISSUE TITLE
Need to add github repository secrets

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/edu-setu-group26-proj2#9]
The following repository secrets need to be added in github secrets:
SMTP_EMAIL
SMTP_PASSWORD

**Comment by rahulrk2303** [comment]
I will share the values privately.

**Comment by rahulrk2303** [comment]
Also, secure this file's contents. https://github.com/ekanshsinghal/edu-setu-group26-proj2/blob/main/code/backend/.oci/base_key.pem

@ekanshsinghal Lmk if these are done. Just have to update in code.

**Comment by ekanshsinghal** [comment]
![image](https://user-images.githubusercontent.com/15945880/205753157-7e3fa887-50b1-4c80-bb94-69c9c1fed0a5.png)
Done
